version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: test_sample01
          - DB_USERNAME: root

      - image: circleci/mysql:5.7-ram
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: test_sample01
    steps:
     - checkout

     - run: sudo apt update
     - run: sudo apt-get install libfreetype6-dev
     - run: sudo apt-get install libjpeg62-turbo-dev
     - run: sudo apt-get install libpng-dev
     - run: sudo apt-get install libwebp-dev
     - run: sudo apt-get install libxpm-dev

     - run: sudo docker-php-ext-install pdo_mysql
     - run: sudo docker-php-ext-configure gd --with-freetype --with-jpeg
     - run: sudo docker-php-ext-install -j$(nproc) gd


     - run:
          working_directory: backend/gameMusic
          command: composer install -n --prefer-dist
     - run:
          working_directory: backend/gameMusic
          command: echo "APP_KEY=" > .env.testing
     - run:
          working_directory: backend/gameMusic
          command: php artisan key:generate
     - run:
          working_directory: backend/gameMusic
          command: php artisan migrate
     - run:
          working_directory: backend/gameMusic
          command: ./vendor/bin/phpunit